[default]

sqlInsert = "INSERT INTO etiquetas1 (Quantidade, Material, Cor, Diametro, Mesa, Bico, Origem,codBarras) VALUES (?,?,?,?,?,?,?,?)"
sqlPesquisa = "select MAX(Lote) from etiquetas1"
sqlUpdate = "UPDATE etiquetas1 SET codBarras = ? WHERE lote = ?"
sqlApaga = "delete from etiquetas1"
sqlZerabanco = "delete from sqlite_sequence where name='etiquetas1'"
sqlSelect = "SELECT * FROM etiquetas1 WHERE Lote = ?"

#Dados do relatorio
tipoPagina = "A4"
folhaEtiquetas = 28
folhaNome = 'imagens/hello_world.pdf'
logoPG3D = 'imagens/Logo.svg'
#Posição verical - LOGO
imagemVertical1 = 30
imagemVertical2 = 190
imagemVertical3 = 350
imagemVertical4 = 510
#Posição horizontal - LOGO
imagemHorizontal1 = 750
imagemHorizontal2 = 640
imagemHorizontal3 = 530
imagemHorizontal4 = 420
imagemHorizontal5 = 310
imagemHorizontal6 = 200
imagemHorizontal7 = 90

recuoVertical = 160
recuoHorizontal = 110

#sqlCadastros = "SELECT * FROM usuario where dataCadastro >= date(?) AND dataCadastro <  date(?, '+1 day')"
#sqlCadPeriodo ="SELECT * FROM usuario where dataCadastro BETWEEN (?) AND date(?, '+1 day')"
#sqlAtualizacao = "SELECT * FROM usuario where dataAtualizacao >= date(?) AND dataAtualizacao <  date(?, '+1 day')"
#sqlAtuPeriodo ="SELECT * FROM usuario where dataAtualizacao BETWEEN (?) AND date(?, '+1 day')"
#arquivoNovos = "dadosCadastros.json"
#arquivosAlterados = "dadosAlterados.json"


